name: CI-CD Backend Deploy
on:
  push:
    branches: [main]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          sync: true
          script: |
            cd build/  
            cd webapp-ui/
            git remote set-url origin https://cin12211:${{ secrets.GIT_TOKEN }}@github.com/Finder-Application/webapp-ui.git
            git pull origin main
            cd ..
            docker compose up --build front-end -d
