name: CI-CD FE Deploy
on:
  push:
    branches: [main]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          sync: true
          script: |
            cd build/  
            cd webapp-ui/
            git pull origin
            cd ..
            ls
            docker ps
            docker compose up --build front-end -d
